### ISSUE TITLE
Isssue with GitHub Actions CI  

### ISSUE THREAD

**Issue by amolbujade** [VisionITTesting/question-and-answer-forum#10]
after pushing some code in github nothing come in actions tab
![Screenshot (41)](https://user-i
![Screenshot (41)](https://user-images.githubusercontent.com/39951851/100057563-26954200-2e41-11eb-870a-c59fdaa33a07.png)

**Comment by akashdktyagi** [comment]
First of all its not "Jenkins CI". You should refer it as "GitHub Actions CI".
Secondly, go and check the maven.yml file. It is sensitive to "master" branch and not "main" branch.
`on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
`
So either create a "master" branch or change the maven file and replace `[master]` with `[main]'

**Comment by akashdktyagi** [comment]
@amolbujade

**Comment by amolbujade** [comment]
Ok sir

**Comment by akashdktyagi** [comment]
Closing the issue, since no further update.
