### ISSUE TITLE
junit selenium folder structure

### ISSUE THREAD

**Issue by surajsb7** [VisionITTesting/question-and-answer-forum#11]
I am facing difficulty to understand the maven folder structure, also showing some warning signs on the Project name please guide us.
![maven folder structure](https://user-images.githubusercontent.com/50292035/100321717-1f109d00-2fe9-11eb-8089-d8ab2c1e93dc.JPG)
![steps](https://user-images.githubusercontent.com/50292035/100321725-233cba80-2fe9-11eb-831d-70dc8e5c879d.JPG)

**Comment by akashdktyagi** [comment]
1. Warning is ok. Ignore them.
2. Add these lines in your pom.xml file. You have missed maven compiler setting. After you add this setting and save pom file. 
`
	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<maven.compiler.source>1.8</maven.compiler.source>
		<maven.compiler.target>1.8</maven.compiler.target>
	</properties>
`
3. After above lines are added and saved, right click on the project, go to "maven" menu option and click on "update project" button.
![image](https://user-images.githubusercontent.com/10477349/100371377-ada70d80-302d-11eb-9a17-3e2d5ac84fff.png)

4. Select your project and click on "ok".
![image](https://user-images.githubusercontent.com/10477349/100371489-d6c79e00-302d-11eb-8625-d928ac786ceb.png)

5. After this project will refresh and jdk version will change from "1.5" to "1.8" and will look like below:
![image](https://user-images.githubusercontent.com/10477349/100371578-feb70180-302d-11eb-9837-91f45b7a7c58.png)

6. Ignore these folders, they just mirror the above folders.

![image](https://user-images.githubusercontent.com/10477349/100371619-14c4c200-302e-11eb-967d-4624457a0b15.png)

@surajsb7

**Comment by surajsb7** [comment]
Okay sir, I will try this.
