### ISSUE TITLE
Maven command line 

### ISSUE THREAD

**Issue by manishvolt** [VisionITTesting/question-and-answer-forum#12]
how do i run my code using maven command line ? I am not getting from where to launch/use the maven command line. 
<img width="942" alt="Untitled" src="https://user-images.githubusercontent.com/73346721/100369151-8d298400-302a-11eb-8e00-259a637c8cc4.png">

**Comment by akashdktyagi** [comment]
You can run maven project in many ways:
1. Run from Eclipse, Right click on the project (not the individual test case class file, maven compiles and run the full project) and click on "Run As" and select "maven install".  Check the screen shot.
![image](https://user-images.githubusercontent.com/10477349/100370380-2d33dd00-302c-11eb-9e2b-4e5d38ed7df9.png)

2. Open command line tool and navigate using "cd" command till the project folder, i.e. parent folder of the pom.xml file and run command" `mvn clean install`

**Comment by akashdktyagi** [comment]
@manishvolt
