### ISSUE TITLE
mvn clean install error

### ISSUE THREAD

**Issue by manishvolt** [VisionITTesting/question-and-answer-forum#13]
i get this error in console when i do mvn clean install -Dbrowser=chrome. please suggest
<img width="869" alt="Untitled" src="https://user-images.githubusercontent.com/73346721/100391844-d09be680-305a-11eb-861e-e4f1ec9e63e9.png">

**Comment by manishvolt** [comment]
don't know what went wrong ! but now, none of my other programs are being executed. problems started occurring after i tried using maven command line (mvn clean install). please help !  
<img width="815" alt="Untitled" src="https://user-images.githubusercontent.com/73346721/100392145-a0a11300-305b-11eb-85d9-afd6ad9ba976.png">

**Comment by akashdktyagi** [comment]
@manishvolt not sure, can u send me the link to the repo, i will have a look

**Comment by akashdktyagi** [comment]
@manishvolt is it solved yet?

**Comment by manishvolt** [comment]
@akashdktyagi yes i figured it out. we can close this issue.
