### ISSUE TITLE
erros in my pom.xml file

### ISSUE THREAD

**Issue by manishvolt** [VisionITTesting/question-and-answer-forum#16]
<img width="832" alt="Untitled" src="https://user-images.githubusercontent.com/73346721/102014795-d6453c00-3d7d-11eb-8bf1-50acf0001f06.png">

i copied cucumber dependencies in my pom.xml file. But getting some errors. what am i doing wrong here ?

**Comment by akashdktyagi** [comment]
Do u have cucumber version mentioned under the properties tag of the pom?

**Comment by akashdktyagi** [comment]
@manishvolt

**Comment by manishvolt** [comment]
Copied the properties from your github code. It worked now
