### ISSUE TITLE
I am Fasing issue while running TestRunner.java file I select junit to run this file (Cucumber framework)

### ISSUE THREAD

**Issue by surajsb7** [VisionITTesting/question-and-answer-forum#17]
![cucumber](https://user-images.githubusercontent.com/50292035/102204042-5c34c480-3eef-11eb-8ba8-1791e0471439.jpg)
![cucumber2](https://user-images.githubusercontent.com/50292035/102204109-6f479480-3eef-11eb-927d-956d729c5c0a.jpg)
@akashdktyagi

**Comment by akashdktyagi** [comment]
@surajsb7 
Check the error message, in the 2nd line its written that "No features found at classpath:features" This means that cucumber is trying to find the features file under "src/test/resources/features" folder. But your project do not have any "features" folder under the "test/resources". So create one and place your feature file under it.

Another suggestion, this has nothing to with the error.
1. Install Cucumber Gherkin plugin. Go to help, market place, and search cucumber and install cucumber plugin and then restart. This way your feature files will be properly highlighted.

**Comment by Roshani26149** [comment]
@surajsb7 
 Inside the test runner file, you wrote features=classpath:feature. instead of that you just give the path of feature file.
Step: right click on feature file-go to properties-you will see the location. Just copy that location and paste it like features="  "; then it will work. or you can do this first create package i.e. Features and inside that put your feature file. and write that features=classpath:Features.

**Comment by surajsb7** [comment]
I worked on the above points now it is working.

**Comment by akashdktyagi** [comment]
> @surajsb7
> Inside the test runner file, you wrote features=classpath:feature. instead of that you just give the path of feature file.
> Step: right click on feature file-go to properties-you will see the location. Just copy that location and paste it like features=" "; then it will work. or you can do this first create package i.e. Features and inside that put your feature file. and write that features=classpath:Features.

Thanks Roshini for answering this. Much appreciated. 👍
