### ISSUE TITLE
Facing the error while running TestRunner and feature file. After adding the 2nd test case. Running smoothly on the single test case.(Cucumber)

### ISSUE THREAD

**Issue by surajsb7** [VisionITTesting/question-and-answer-forum#22]
![Feature_file_error](https://user-images.githubusercontent.com/50292035/103435780-b3e66600-4c39-11eb-8201-9d77aa2ddb70.JPG)
![TestRunner_error](https://user-images.githubusercontent.com/50292035/103435789-c3fe4580-4c39-11eb-988f-fdfd2c2471cd.JPG)
![error3_Console](https://user-images.githubusercontent.com/50292035/103435792-c8c2f980-4c39-11eb-941f-c6a0fff50e9c.JPG)
![testcase1](https://user-images.githubusercontent.com/50292035/103435794-cf517100-4c39-11eb-8d31-0fd1fbd63193.JPG)
![testcase2](https://user-images.githubusercontent.com/50292035/103435796-d4162500-4c39-11eb-8110-2b415bc13240.JPG)
@akashdktyagi

**Comment by akashdktyagi** [comment]
@surajsb7 check the 2nd screen shot. there is error which says, Duplicate step def. The thing is that you can not have two methods with the same annotation. That means, that one Step in a gherkin file need to have only one matching method in "all" the stef def class files. Now in your case you have two step def class files and in both the files you have duplicate methods. So now cucumber is confused which method from which class file to call. And thats why it threw you error of "Duplicate Step Definitions". You see, cucumber is telling you the error, its just you ignored it :-)
