### ISSUE TITLE
#3 Below methods are from StringBuilder class, where StringBuilder & AbstractStringBuilder available, how can same class be abstract & concrete

### ISSUE THREAD

**Issue by sarangholey** [VisionITTesting/question-and-answer-forum#3]

**Comment by sarangholey** [comment]
![IMG-20201021-WA0001.jpg](https://user-images.githubusercontent.com/43402198/96678963-5d82be80-1390-11eb-8bed-2542cf4ef2e4.jpg)

**Comment by akashdktyagi** [comment]
StringBuilder class is inheriting the methods from AbstractStringBuilder. So this list is telling which method belongs to which class. If the method is not over-ridden then it will show that this method is from the "AbstractStringBuilder" Class. If the method is overridden in the "StringBuilder" class it will be shown as part of "StringBuilder" class.
So for example, method, "codePointBefore" ,method is part of "AbstractStringBuilder" class and is also not overridden by "StringBuilder" class, thats why it is shown as "AbstractStingBuilder" in the question's screen shot.

Check the below class diagram for better understandability:

![image](https://user-images.githubusercontent.com/10477349/100375527-eea22080-3033-11eb-9f90-a42ed6ab9ca8.png)

Also, try to walk through the StringBuilder class and see how it is implemented.

![Uploading image.png…]()
