### ISSUE TITLE
Are Parameter and Argument same? when we say parameter and when argument?

### ISSUE THREAD

**Issue by Roshani26149** [VisionITTesting/question-and-answer-forum#7]
employee(int salary, String name) {};
So salary  and name are parameter Or argument??

**Comment by akashdktyagi** [comment]
Parameter and arguments are "almost" one and the same thing. Parameter is a more genetic term however.  Usually, when you refer to a method you can say argument i.e. employee accepts two arguments. But if you say employee accepts two parameters, it is still means the same thing.

**Comment by akashdktyagi** [comment]
@Roshani26149
