### ISSUE TITLE
What is Difference between WebDriver driver; and WebDriver driver=null;

### ISSUE THREAD

**Issue by Roshani26149** [VisionITTesting/question-and-answer-forum#8]

**Comment by akashdktyagi** [comment]
Its always a good practice to write `WebDriver driver=null`; this is how you are telling the compiler that the object reference is  null and that you have initialised the variable. Compiler like initialised variables. All the class instance variables automatically initialises with default values. (the variables which we declare at the top are called instance variables)  . Numbers will be initialised with 0, boolean with false and objects with null value. If the variables are inside the methods then compiler will throw error and ask you to initialise them the moment you try to use them.
I have re-created all the three scenarios in below screen shot. Please check and ask if any further questions in comments.
automatically initialise with default values
