### ISSUE TITLE
problem facing during code push on git hub

### ISSUE THREAD

**Issue by Sujeet4642** [VisionITTesting/question-and-answer-forum#9]
i pushed my code on github, after adding one new test case and try to push then it shows me error
![Screenshot (27)](https://user-images.githubusercontent.com/63950829/100000954-611ec080-2de8-11eb-81dd-150437d8cd6c.png)

**Comment by akashdktyagi** [comment]
This error represents that you are trying to push some changes to the repository with out taking latest from the repository.
To resolve this take latest from the repository by running the command: 
`git pull origin <branch_name>` in your case command would look like: `git pull origin main`

**Comment by Sujeet4642** [comment]
In my repository there is no master branch it shows main branch as default

**Comment by akashdktyagi** [comment]
@Sujeet4642 so push in main branch. By the way u can create a master branch as well

**Comment by Sujeet4642** [comment]
Ok sir

**Comment by Sujeet4642** [comment]
solved my problem
